project:
  type: website
  output-dir: _site
plugins:
    - last_modified
website:
  title: "Documentation"
  favicon: _pictures/favicon.ico
  page-footer:
    right: "Built using [Quarto](https://quarto.org)"
    left: |
      In collaboration with 
      [![](https://mountainland.org/static/media/logo/svg/MAG_Logo_Horz_NoTag.svg){fig-alt='MAG' width=65px}](https://mountainland.org/)
  navbar:
    background: info
    logo: _pictures/WFRCDieCutLogo.png
    logo-href: https://wfrc.org
    tools:
      - icon: github
        href: https://github.com/WFRCAnalytics/TDM-Documentation/tree/gh-pages
    title: false
    collapse-below: lg
    left:

      - text: "Overview"
        href: index.qmd

      - text: "What's New?"
        menu:
        - text: "Version 9" 
          href: 1-whats-new/v9-whats-new/index.qmd
          id: v9-wn-index
        - text: "Version 8"
          href: 1-whats-new/v8-whats-new/index.qmd
          id: v8-wn-index
        - text: "Version 7"
          href: 1-whats-new/v7-whats-new/index.qmd
          id: v7-wn-index

      - text: "Model Documentation"
        menu:
        - text: "Version 7"
          href: 2-model-documentation/v7_Documentation/index.qmd
          id: v7-index
        - text: "Version 6"
          href: 2-model-documentation/v6_Documentation/index.qmd
          id: v6-index

      - text: "Calibration/Validation"
        menu:
        - text: "Version 8.3.1"
          href: 3-calib-valid/v831-calib-valid/index.qmd
          id: v831-cv-index

      - text: "Resources"
        href: 4-other/other.qmd

      - text: "Testing"
        menu:
        - text: "Visualization"
          href: 5-testing/jupyter-widgets.qmd
          id: testing-index
          
  sidebar:
    - id: v9-wn-index
      title: "What's New? - Version 9"
      contents:
        - text: "Preface"
          href: 1-whats-new/v9-whats-new/index.qmd
        - section: 'v9.0.0'
          contents:
          - section: '2022-12-19'
            contents: 
              - text: "General Parameters - Comparison with v8.3.2"
                href: 1-whats-new/v9-whats-new/2022-12-19/1-genparams.qmd  
              - text: "Input Data"
                href: 1-whats-new/v9-whats-new/2022-12-19/2-inputdata.qmd
              - text: "Input Processing"
                href: 1-whats-new/v9-whats-new/2022-12-19/3-inputprocessing.qmd
              - text: "Distribution"
                href: 1-whats-new/v9-whats-new/2022-12-19/6-distribution.qmd
          - section: '2022-11-01'
            contents:
              - text: "General Parameters - Comparison with v8.3.2"
                href: 1-whats-new/v9-whats-new/2022-11-01/1-genparams.qmd  
              - text: "Input Data"
                href: 1-whats-new/v9-whats-new/2022-11-01/2-inputdata.qmd
              - text: "Input Processing"
                href: 1-whats-new/v9-whats-new/2022-11-01/3-inputprocessing.qmd
              - text: "Mode Choice"
                href: 1-whats-new/v9-whats-new/2022-11-01/7-mc.qmd
          - section: '2022-10-05'
            contents:
              - text: "General Parameters - Comparison with v8.3.2"
                href: 1-whats-new/v9-whats-new/2022-10-05/1-genparams.qmd  
              - text: "Input Data"
                href: 1-whats-new/v9-whats-new/2022-10-05/2-inputdata.qmd
              - text: "Input Processing"
                href: 1-whats-new/v9-whats-new/2022-10-05/3-inputprocessing.qmd
              - text: "Household Disaggregation and Auto Ownership"
                href: 1-whats-new/v9-whats-new/2022-10-05/4-hhdisag.qmd
              - text: "Mode Choice"
                href: 1-whats-new/v9-whats-new/2022-10-05/7-mc.qmd
              - text: "Highway Assignment"
                href: 1-whats-new/v9-whats-new/2022-10-05/8-assign.qmd
              - text: "Model Results - Comparison with v8.3.2"
                href: 1-whats-new/v9-whats-new/2022-10-05/10-modelresults.qmd  

    - id: v8-wn-index
      title: "What's New? - Version 8"
      contents:
        - text: "Downloads"
          href: 1-whats-new/v8-whats-new/downloads.qmd
        - text: "Preface"
          href: 1-whats-new/v8-whats-new/index.qmd
        - section: 'v8.3.2'
          contents:
          - section: '2022-02-04'
            contents:
            - text: "2022-02-04 Update"
              href: 1-whats-new/v8-whats-new/v832/2022-02-04/1-20220204-update.qmd
          - section: '2021-11-10'
            contents:
            - text: "General Parameters"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/1-genparams.qmd
            - text: "Input Data"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/2-inputdata.qmd
            - text: "Input Processing"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/3-inputprocessing.qmd
            - text: "Household Disaggregation and Auto Ownership"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/4-hhdisag.qmd
            - text: "Trip Generation"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/5-tripgen.qmd
            - text: "Distribution"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/6-distribution.qmd
            - text: "Mode Choice"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/7-mc.qmd
            - text: "Highway Assignment"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/8-assign.qmd
            - text: "Post Processing"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/9-pp.qmd
            - text: "Model Results - Comparison with v8.3.1"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/10-modelresults.qmd
        - section: 'v8.3.1'
          contents:
          - section: '2020-08-17'
            contents:
            - text: '2020-08-17 Update'
              href: 1-whats-new/v8-whats-new/v831/2020-08-17/1-20200817-update.qmd
          - section: '2020-05-08'
            contents:
            - text: 'Input Data'
              href: 1-whats-new/v8-whats-new/v831/2020-05-08/1-inputdata.qmd
            - text: 'Update for Cube 6.4.5'
              href: 1-whats-new/v8-whats-new/v831/2020-05-08/2-cube-update.qmd
            - text: 'Segment Summary'
              href: 1-whats-new/v8-whats-new/v831/2020-05-08/3-segsum.qmd
            - text: 'Assignment Output Folder'
              href: 1-whats-new/v8-whats-new/v831/2020-05-08/4-assign.qmd
            - text: 'Access to Opportunity'
              href: 1-whats-new/v8-whats-new/v831/2020-05-08/5-ato.qmd
            - text: 'Miscellaneous Changes'
              href: 1-whats-new/v8-whats-new/v831/2020-05-08/6-misc.qmd

    - id: v7-wn-index
      title: "What's New? - Version 7"     
      contents:
        - text: "Downloads"
          href: 1-whats-new/v7-whats-new/downloads.qmd
        - text: "Preface"
          href: 1-whats-new/v7-whats-new/index.qmd
        - section: 'v7.0.2'
          contents:
          - section: '2012-06'
            contents:
            - text: "2012-06 Update"
              href: 1-whats-new/v7-whats-new/v702/1-201206-update.qmd 
            - text: "BRT Modes"
              href: 1-whats-new/v7-whats-new/v702/2-modes.qmd
            - text: "Hand Coded Access Links"
              href: 1-whats-new/v7-whats-new/v702/3-accesslinks.qmd
            - text: "Other Modifications"
              href: 1-whats-new/v7-whats-new/v702/4-other.qmd
        - section: 'v7.0.1'
          contents:
          - section: '2012-05'
            contents:
            - text: "Hail Mary" 
              href: 1-whats-new/v7-whats-new/v701/1-hailmary.qmd
            - text: "Elapsed Time" 
              href: 1-whats-new/v7-whats-new/v701/2-etime.qmd
            - text: "Model Notification" 
              href: 1-whats-new/v7-whats-new/v701/3-notification.qmd
            - text: "Input/Output File Names" 
              href: 1-whats-new/v7-whats-new/v701/4-inputoutput.qmd
            - text: "Voyager Module References" 
              href: 1-whats-new/v7-whats-new/v701/5-module.qmd
            - text: "General Updates" 
              href: 1-whats-new/v7-whats-new/v701/6-general.qmd


    - id: v831-cv-index
      title: "Calibration/Validation - Version 8.3.1"
    - id: v6-index
      title: "Complete Model Documentation - Version 6"
    - id: v7-index
      title: "Complete Model Documentation - Version 7"
    - id: testing-index
      title: "Testing Environment"
      contents:
        - text: "Jupyter Widgets"
          href: 5-testing/jupyter-widgets.qmd
        - text: "Example OJS"
          href: 5-testing/ojs-test.qmd

format:
  html:
    toc: true
    theme:
      - cerulean
      - custom.css
    code-fold: true
  pdf:
    documentclass: scrreprt




