project:
  type: website
  output-dir: docs

website:
  title: "Documentation"
  page-footer:
    right: "Built using [Quarto](https://quarto.org)"
    left: "An online documentation for WFRC's Travel Demand Model"
  navbar:
    background: light
    title: false
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "What's New?"
        menu:
        - text: "Version 8.3.2"
          href: v832-whats-new/index.qmd
          id: v832-index
        - text: "Version 9" 
          href: v9-whats-new/index.qmd
          id: v9-index
      - text: "Testing"
        menu:
        - text: "Visualization"
          href: testing/jupyter-widgets.qmd
          id: testing-index
          
  sidebar:
    - id: v832-index
      title: "What's New? - Version 8.3.2"
      contents:
        - text: "Preface"
          href: v832-whats-new/index.qmd
        - text: "2022-02-04 UPDATE"
          href: v832-whats-new/1-20220204-update.qmd
        - text: "1 General Parameters"
          href: v832-whats-new/1-genparams.qmd
        - text: "2 Input Data"
          href: v832-whats-new/2-inputdata.qmd
        - text: "3 Input Processing"
          href: v832-whats-new/3-inputprocessing.qmd
        - text: "4 Household Disaggregation and Auto Ownership"
          href: v832-whats-new/4-hhdisag.qmd
        - text: "5 Trip Generation"
          href: v832-whats-new/5-tripgen.qmd
        - text: "6 Distribution"
          href: v832-whats-new/6-distribution.qmd
        - text: "7 Mode Choice"
          href: v832-whats-new/7-mc.qmd
        - text: "8 Highway Assignment"
          href: v832-whats-new/8-assign.qmd
        - text: "9 Post Processing"
          href: v832-whats-new/9-pp.qmd
        - text: "10 Model Results - Comparison with v8.3.1"
          href: v832-whats-new/10-modelresults.qmd
    - id: v9-index
      title: "What's New? - Version 9"
      contents:
        - text: "Preface"
          href: v9-whats-new/index.qmd
        - text: "10 Model Results - Comparison with v9.0"
          href: v9-whats-new/10-modelresults.qmd  
    - id: testing-index
      title: "Testing Environment"
      contents:
        - text: "Jupyter Widgets"
          href: testing/jupyter-widgets.qmd
        - text: "Example OJS"
          href: testing/ojs-test.qmd

format:
  html:
    toc: true
    theme:
      - cosmo
      - custom.css
    code-fold: true





