
#==================
#v9-v900-whats-new
#==================

#project:
#  type: book
#  output-dir: _book/v9x-v900-whats-new-pdf 
#  #output-dir: _book/v9x-v900-whats-new-doc
#
#book:
#  title: "What's New? - Version 9.0.0"
#  author: "WFRC / MAG"
#  date: "6/9/2023"
#  chapters:
#    - index.qmd
#    - v9x/v900/whats-new/1-genparams.qmd
#    - v9x/v900/whats-new/2-inputdata.qmd
#    - v9x/v900/whats-new/3-inputprocessing.qmd
#    - v9x/v900/whats-new/4-hhdisag.qmd
#    - v9x/v900/whats-new/6-distribution.qmd
#    - v9x/v900/whats-new/7-mc.qmd
#    - v9x/v900/whats-new/8-assign.qmd
#    - v9x/v900/whats-new/10-modelresults.qmd


#===================
#v9-v900-validation
#===================
  
#project:
#  type: book
#  #output-dir: _book/v9x-v900-validation-pdf
#  output-dir: _book/v9x-v900-validation-doc#

#book:
#  title: "Validation Report - Version 9.0.0"
#  author: "WFRC / MAG"
#  date: "6/9/2023"
#  chapters:
#    - index.qmd
#    - v9x/v900/validation/1-life-cycle.qmd
#    - v9x/v900/validation/2-hh-disagg.qmd
#    - v9x/v900/validation/3-auto-own.qmd
#    - v9x/v900/validation/4-trip-gen.qmd
#    - v9x/v900/validation/5-distribution.qmd
#    - v9x/v900/validation/6-mc.qmd
#    - v9x/v900/validation/7-assign.qmd
#    - v9x/v900/validation/8-sensitivity.qmd


#======================
#v9-v900-model-process
#======================
  
project:
  type: book
  output-dir: _book/v9x-v900-model-process-pdf
  #output-dir: _book/v9x-v900-model-process-doc

book:
  title: "Model Process Report - Version 9.0.0"
  author: "WFRC / MAG"
  date: "6/9/2023"
  chapters:
    - index.qmd
    - v9x/v900/model-process/1-life-cycle.qmd
    - v9x/v900/model-process/2-hh-disagg.qmd
    - v9x/v900/model-process/3-auto-own.qmd
    - v9x/v900/model-process/4-trip-gen.qmd
    - v9x/v900/model-process/5-distribution.qmd
    - v9x/v900/model-process/6-mc.qmd
    - v9x/v900/model-process/7-assign.qmd
    - v9x/v900/model-process/8-sensitivity.qmd


format:
  RtpPDF-pdf:
    toc: true
    lot: true
    lof: true
    number-sections: true
    colorlinks: true
    tbl-colwidths: [70, 30]
    classoption:
      - 'titlepage=false'
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
  #docx: 
  #  reference-doc: _extensions/cday/template-rtp.docx
  
  