project:
  type: website
  output-dir: _site
plugins:
    - last_modified
website:
  title: "Documentation"
  favicon: _pictures/favicon.ico
  page-footer:
    right: "Built using [Quarto](https://quarto.org)"
    left: |
      [![](https://wfrc.org/wp-content/uploads/2021/11/logo.jpg){fig-alt='WFRC' width=150px}](https://wfrc.org) 
      [![](https://mountainland.org/static/media/logo/svg/MAG_Logo_Horz_NoTag.svg){fig-alt='MAG' width=65px}](https://mountainland.org/)
  navbar:
    background: info
    logo: _pictures/wf-logo-new-white-t.png
    logo-href: https://wfrc.org
    tools:
      - icon: github
        href: https://github.com/WFRCAnalytics/TDM-Documentation/tree/gh-pages
    title: false
    collapse-below: lg
    left:

      - text: "Overview"
        href: index.qmd

      - text: "What's New?"
        menu:
        - text: "Version 9" 
          href: 1-whats-new/v9-whats-new/index.qmd
          id: v9-wn-index
        - text: "Version 8"
          href: 1-whats-new/v8-whats-new/index.qmd
          id: v8-wn-index
        - text: "Version 7"
          href: 1-whats-new/v7-whats-new/index.qmd
          id: v7-wn-index
        - text: "Previous Versions"
          href: 1-whats-new/v3-v6-whats-new/index.qmd
          id: v3-v6-wn-index

      - text: "Inputs"
        menu:
        - text: "Version 8"
          href: 2-inputs/v8-inputs/index.qmd
          id: v8-in-index

      - text: "Calibration/Validation"
        menu:
        - text: "Version 8"
          href: 3-calib-valid/v8-calib-valid/index.qmd
          id: v8-cv-index

      - text: "Other"
        href: 4-other/intro.qmd
        id: other-index

      - text: "Testing"
        menu:
        - text: "Visualization"
          href: 5-testing/jupyter-widgets.qmd
          id: testing-index
          
  sidebar:
    - id: v9-wn-index
      title: "What's New? - Version 9"
      contents:
        - text: "Preface"
          href: 1-whats-new/v9-whats-new/index.qmd
        - section: 'v9.0.0'
          contents:
          - section: '2022-12-19'
            contents: 
              - text: "General Parameters - Comparison with v8.3.2"
                href: 1-whats-new/v9-whats-new/2022-12-19/1-genparams.qmd  
              - text: "Input Data"
                href: 1-whats-new/v9-whats-new/2022-12-19/2-inputdata.qmd
              - text: "Input Processing"
                href: 1-whats-new/v9-whats-new/2022-12-19/3-inputprocessing.qmd
              - text: "Distribution"
                href: 1-whats-new/v9-whats-new/2022-12-19/6-distribution.qmd
          - section: '2022-11-01'
            contents:
              - text: "General Parameters - Comparison with v8.3.2"
                href: 1-whats-new/v9-whats-new/2022-11-01/1-genparams.qmd  
              - text: "Input Data"
                href: 1-whats-new/v9-whats-new/2022-11-01/2-inputdata.qmd
              - text: "Input Processing"
                href: 1-whats-new/v9-whats-new/2022-11-01/3-inputprocessing.qmd
              - text: "Mode Choice"
                href: 1-whats-new/v9-whats-new/2022-11-01/7-mc.qmd
          - section: '2022-10-05'
            contents:
              - text: "General Parameters - Comparison with v8.3.2"
                href: 1-whats-new/v9-whats-new/2022-10-05/1-genparams.qmd  
              - text: "Input Data"
                href: 1-whats-new/v9-whats-new/2022-10-05/2-inputdata.qmd
              - text: "Input Processing"
                href: 1-whats-new/v9-whats-new/2022-10-05/3-inputprocessing.qmd
              - text: "Household Disaggregation and Auto Ownership"
                href: 1-whats-new/v9-whats-new/2022-10-05/4-hhdisag.qmd
              - text: "Mode Choice"
                href: 1-whats-new/v9-whats-new/2022-10-05/7-mc.qmd
              - text: "Highway Assignment"
                href: 1-whats-new/v9-whats-new/2022-10-05/8-assign.qmd
              - text: "Model Results - Comparison with v8.3.2"
                href: 1-whats-new/v9-whats-new/2022-10-05/10-modelresults.qmd  

    - id: v8-wn-index
      title: "What's New? - Version 8"
      contents:
        - text: "Downloads"
          href: 1-whats-new/v8-whats-new/downloads.qmd
        - text: "Preface"
          href: 1-whats-new/v8-whats-new/index.qmd
        - section: 'v8.3.2'
          contents:
          - section: '2022-02-04'
            contents:
            - text: "2022-02-04 Update"
              href: 1-whats-new/v8-whats-new/v832/2022-02-04/1-20220204-update.qmd
          - section: '2021-11-10'
            contents:
            - text: "General Parameters"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/1-genparams.qmd
            - text: "Input Data"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/2-inputdata.qmd
            - text: "Input Processing"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/3-inputprocessing.qmd
            - text: "Household Disaggregation and Auto Ownership"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/4-hhdisag.qmd
            - text: "Trip Generation"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/5-tripgen.qmd
            - text: "Distribution"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/6-distribution.qmd
            - text: "Mode Choice"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/7-mc.qmd
            - text: "Highway Assignment"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/8-assign.qmd
            - text: "Post Processing"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/9-pp.qmd
            - text: "Model Results - Comparison with v8.3.1"
              href: 1-whats-new/v8-whats-new/v832/2021-11-10/10-modelresults.qmd
        - section: 'v8.3.1'
          contents:
          - section: '2020-08-17'
            contents:
            - text: '2020-08-17 Update'
              href: 1-whats-new/v8-whats-new/v831/2020-08-17/1-20200817-update.qmd
          - section: '2020-05-08'
            contents:
            - text: 'Input Data'
              href: 1-whats-new/v8-whats-new/v831/2020-05-08/1-inputdata.qmd
            - text: 'Update for Cube 6.4.5'
              href: 1-whats-new/v8-whats-new/v831/2020-05-08/2-cube-update.qmd
            - text: 'Segment Summary'
              href: 1-whats-new/v8-whats-new/v831/2020-05-08/3-segsum.qmd
            - text: 'Assignment Output Folder'
              href: 1-whats-new/v8-whats-new/v831/2020-05-08/4-assign.qmd
            - text: 'Access to Opportunity'
              href: 1-whats-new/v8-whats-new/v831/2020-05-08/5-ato.qmd
            - text: 'Miscellaneous Changes'
              href: 1-whats-new/v8-whats-new/v831/2020-05-08/6-misc.qmd

    - id: v7-wn-index
      title: "What's New? - Version 7"     
      contents:
        - text: "Downloads"
          href: 1-whats-new/v7-whats-new/downloads.qmd
        - text: "Preface"
          href: 1-whats-new/v7-whats-new/index.qmd
        - section: 'v7.0.2'
          contents:
          - section: '2012-06'
            contents:
            - text: "2012-06 Update"
              href: 1-whats-new/v7-whats-new/v702/1-201206-update.qmd 
            - text: "BRT Modes"
              href: 1-whats-new/v7-whats-new/v702/2-modes.qmd
            - text: "Hand Coded Access Links"
              href: 1-whats-new/v7-whats-new/v702/3-accesslinks.qmd
            - text: "Other Modifications"
              href: 1-whats-new/v7-whats-new/v702/4-other.qmd
        - section: 'v7.0.1'
          contents:
          - section: '2012-05'
            contents:
            - text: "Hail Mary" 
              href: 1-whats-new/v7-whats-new/v701/1-hailmary.qmd
            - text: "Elapsed Time" 
              href: 1-whats-new/v7-whats-new/v701/2-etime.qmd
            - text: "Model Notification" 
              href: 1-whats-new/v7-whats-new/v701/3-notification.qmd
            - text: "Input/Output File Names" 
              href: 1-whats-new/v7-whats-new/v701/4-inputoutput.qmd
            - text: "Voyager Module References" 
              href: 1-whats-new/v7-whats-new/v701/5-module.qmd
            - text: "General Updates" 
              href: 1-whats-new/v7-whats-new/v701/6-general.qmd
    - id: v3-v6-wn-index
      title: "What's New? - Versions 3, 4, 5, & 6"
      contents:
        - text: "Downloads"
          href: 1-whats-new/v3-v6-whats-new/downloads.qmd
        - text: "Preface"
          href: 1-whats-new/v3-v6-whats-new/index.qmd
        - section: "Version 6"
          contents: 
          - section: "Version 6.1"
            contents: 
            - text: "Overview"
              href: 1-whats-new/v3-v6-whats-new/v6/v61-overview.qmd
          - section: "Version 6.0 - 12/12/2005"
            contents: 
            - text: "Introduction"
              href: 1-whats-new/v3-v6-whats-new/v6/v6-intro.qmd
            - text: "When to Use Improvements"
              href: 1-whats-new/v3-v6-whats-new/v6/v6-when.qmd
            - text: "What's New Summary"
              href: 1-whats-new/v3-v6-whats-new/v6/v6-wn.qmd
            - text: "Development Plans"
              href: 1-whats-new/v3-v6-whats-new/v6/v6-improvements.qmd
        - section: "Version 5"
          contents:
          - section: "Version 5.0 - 12/12/2005"
            contents:
            - text: "Introduction"
              href: 1-whats-new/v3-v6-whats-new/v5/v5-intro.qmd
            - text: "When to Use Improvements"
              href: 1-whats-new/v3-v6-whats-new/v5/v5-when.qmd
            - text: "What's New Summary"
              href: 1-whats-new/v3-v6-whats-new/v5/v5-wn.qmd
            - text: "Development Plans"
              href: 1-whats-new/v3-v6-whats-new/v5/v5-improvements.qmd
        - section: "Version 4"
          contents:
          - section: "Version 4.3 - 04/05/2005"
            contents:
            - text: "Introduction"
              href: 1-whats-new/v3-v6-whats-new/v4/v43-intro.qmd
            - text: "When to Use Improvements"
              href: 1-whats-new/v3-v6-whats-new/v4/v43-when.qmd
            - text: "What's New Summary"
              href: 1-whats-new/v3-v6-whats-new/v4/v43-wn.qmd
            - text: "Development Plans"
              href: 1-whats-new/v3-v6-whats-new/v4/v43-improvements.qmd
          - section: "Version 4.2 - 08/30/2004"
            contents:
            - text: "Introduction"
              href: 1-whats-new/v3-v6-whats-new/v4/v42-intro.qmd
            - text: "When to Use Improvements"
              href: 1-whats-new/v3-v6-whats-new/v4/v42-when.qmd
            - text: "Why v4.0 and v4.1 were Necessary"
              href: 1-whats-new/v3-v6-whats-new/v4/v42-necessary.qmd 
            - text: "What's New Summary"
              href: 1-whats-new/v3-v6-whats-new/v4/v42-wn.qmd
            - text: "New Features"
              href: 1-whats-new/v3-v6-whats-new/v4/v42-new-features.qmd
            - text: "Development Plans"
              href: 1-whats-new/v3-v6-whats-new/v4/v42-improvements.qmd
            - text: "Terms and Abbreviations"
              href: 1-whats-new/v3-v6-whats-new/v4/v42-terms.qmd
          - section: "Version 4.0 - 05/01/2004"
            contents:
            - text: "Overview"
              href: 1-whats-new/v3-v6-whats-new/v4/v40-overview.qmd
        - section: "Version 3"
          contents:
          - section: "Version 3.2 - 02/10/2004"
            contents:
            - text: "Introduction"
              href: 1-whats-new/v3-v6-whats-new/v3/v32-intro.qmd
            - text: "Why v3.2 was Necessary"
              href: 1-whats-new/v3-v6-whats-new/v3/v32-necessary.qmd
            - text: "Input Preparation"
              href: 1-whats-new/v3-v6-whats-new/v3/v32-input-prep.qmd
            - text: "Mode Choice"
              href: 1-whats-new/v3-v6-whats-new/v3/v32-mode-choice.qmd
            - text: "District Analysis Tool"
              href: 1-whats-new/v3-v6-whats-new/v3/v32-district-analysis.qmd
            - text: "Highway Analysis Tool"
              href: 1-whats-new/v3-v6-whats-new/v3/v32-hway-analysis.qmd
            - text: "Terms and Abbreviations"
              href: 1-whats-new/v3-v6-whats-new/v3/v32-terms.qmd
          - section: "Version 3.1"
            contents:
            - text: "Introduction - 07/23/2003"
              href: 1-whats-new/v3-v6-whats-new/v3/v31-intro.qmd
            - text: "Input Preparation"
              href: 1-whats-new/v3-v6-whats-new/v3/v31-input-prep.qmd
            - text: "Mode Choice"
              href: 1-whats-new/v3-v6-whats-new/v3/v31-mode-choice.qmd
          - section: "Version 3.0 - 06/25/2003"
            contents:
            - text: "Documentation & Source Files"
              href: 1-whats-new/v3-v6-whats-new/v3/v30-doc.qmd
            - text: "Input Preparation"
              href: 1-whats-new/v3-v6-whats-new/v3/v30-input-prep.qmd
            - text: "Modeling Process"
              href: 1-whats-new/v3-v6-whats-new/v3/v30-modeling-process.qmd
            - text: "Auto Ownership Model"
              href: 1-whats-new/v3-v6-whats-new/v3/v30-auto-own.qmd
            - text: "Trip Generation"
              href: 1-whats-new/v3-v6-whats-new/v3/v30-trip-gen.qmd
            - text: "Trip Distribution"
              href: 1-whats-new/v3-v6-whats-new/v3/v30-distribution.qmd
            - text: "Mode Choice"
              href: 1-whats-new/v3-v6-whats-new/v3/v30-mode-choice.qmd
            - text: "Highway Assignment"
              href: 1-whats-new/v3-v6-whats-new/v3/v30-assign.qmd
            - text: "Reports, Post Processors, Data Management"
              href: 1-whats-new/v3-v6-whats-new/v3/v30-reports.qmd
            - text: "Terms and Abbreviations"
              href: 1-whats-new/v3-v6-whats-new/v3/v30-terms.qmd

    - id: v8-in-index
      title: "Inputs - Version 8"
      contents:
        - text: "Downloads"
          href: 2-inputs/v8-inputs/downloads.qmd
        - text: "Preface"
          href: 2-inputs/v8-inputs/index.qmd

    - id: v8-cv-index
      title: "Inputs - Version 8"
      contents:
        - text: "Downloads"
          href: 3-calib-valid/v8-calib-valid/downloads.qmd
        - text: "Preface"
          href: 3-calib-valid/v8-calib-valid/index.qmd
    
    - id: other-index
      title: "Other Documentation"
      contents:
        - text: "Preface"
          href: 4-other/intro.qmd
        - text: "Model Documentation"
          href: 4-other/model-doc.qmd
        - text: "User Guides"
          href: 4-other/user-guides.qmd
        - text: "Other Documentation"
          href: 4-other/other.qmd

    - id: testing-index
      title: "Testing Environment"
      contents:
        - text: "Jupyter Widgets"
          href: 5-testing/jupyter-widgets.qmd
        - text: "Example OJS"
          href: 5-testing/ojs-test.qmd

format:
  html:
    toc: true
    theme:
      - cerulean
      - custom.css
    code-fold: true
  pdf:
    documentclass: scrreprt




