project:
  type: website
  output-dir: _site
plugins:
    - last_modified
website:
  title: "Documentation"
  favicon: _pictures/favicon.ico
  page-footer:
    right: "Built using [Quarto](https://quarto.org)"
    left: In collaboration with [![](_pictures/mag-logo.png){fig-alt='MAG' width=65px}](https://mountainland.org/)
    #center: "Last updated: $(last_modified_date)"
  navbar:
    background: info
    logo: _pictures/WFRCDieCutLogo.png
    logo-href: https://wfrc.org
    tools:
      - icon: github
        href: https://github.com/WFRCAnalytics/TDM-Documentation
    title: false
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd
      - text: "What's New?"
        menu:
        - text: "Version 9" 
          href: 1-whats-new/v9-whats-new/index.qmd
          id: v9-wn-index
        - text: "Version 8.3.2"
          href: 1-whats-new/v832-whats-new/index.qmd
          id: v832-wn-index
        - text: "Version 8.3.1"
          href: 1-whats-new/v831-whats-new/index.qmd
          id: v831-wn-index
      - text: "Model Documentation"
        menu:
        - text: "Version 7"
          href: 2-model-documentation/v7_Documentation/index.qmd
          id: v7-index
        - text: "Version 6"
          href: 2-model-documentation/v6_Documentation/index.qmd
          id: v6-index
      - text: "Calibration/Validation"
        menu:
        - text: "Version 8.3.1"
          href: 3-calib-valid/v831-calib-valid/index.qmd
          id: v831-cv-index
      - text: "Resources"
        href: 4-other/other.qmd
      - text: "Testing"
        menu:
        - text: "Visualization"
          href: 5-testing/jupyter-widgets.qmd
          id: testing-index
          
  sidebar:
    - id: v832-wn-index
      title: "What's New? - Version 8.3.2"
      contents:
        - text: "Preface"
          href: 1-whats-new/v832-whats-new/index.qmd
        - section: '2022-02-04'
          contents:
          - text: "2022-02-04 UPDATE"
            href: 1-whats-new/v832-whats-new/1-20220204-update.qmd
          - text: "1 General Parameters"
            href: 1-whats-new/v832-whats-new/1-genparams.qmd
          - text: "2 Input Data"
            href: 1-whats-new/v832-whats-new/2-inputdata.qmd
          - text: "3 Input Processing"
            href: 1-whats-new/v832-whats-new/3-inputprocessing.qmd
          - text: "4 Household Disaggregation and Auto Ownership"
            href: 1-whats-new/v832-whats-new/4-hhdisag.qmd
          - text: "5 Trip Generation"
            href: 1-whats-new/v832-whats-new/5-tripgen.qmd
          - text: "6 Distribution"
            href: 1-whats-new/v832-whats-new/6-distribution.qmd
          - text: "7 Mode Choice"
            href: 1-whats-new/v832-whats-new/7-mc.qmd
          - text: "8 Highway Assignment"
            href: 1-whats-new/v832-whats-new/8-assign.qmd
          - text: "9 Post Processing"
            href: 1-whats-new/v832-whats-new/9-pp.qmd
          - text: "10 Model Results - Comparison with v8.3.1"
            href: 1-whats-new/v832-whats-new/10-modelresults.qmd
    - id: v9-wn-index
      title: "What's New? - Version 9"
      contents:
        - text: "Preface"
          href: 1-whats-new/v9-whats-new/index.qmd
        - section: '2022-12-19'
          contents: 
            - text: "1 General Parameters - Comparison with v8.3.2"
              href: 1-whats-new/v9-whats-new/2022-12-19/1-genparams.qmd  
            - text: "2 Input Data"
              href: 1-whats-new/v9-whats-new/2022-12-19/2-inputdata.qmd
            - text: "3 Input Processing"
              href: 1-whats-new/v9-whats-new/2022-12-19/3-inputprocessing.qmd
            - text: "6 Distribution"
              href: 1-whats-new/v9-whats-new/2022-12-19/6-distribution.qmd
        - section: '2022-11-01'
          contents:
            - text: "1 General Parameters - Comparison with v8.3.2"
              href: 1-whats-new/v9-whats-new/2022-11-01/1-genparams.qmd  
            - text: "2 Input Data"
              href: 1-whats-new/v9-whats-new/2022-11-01/2-inputdata.qmd
            - text: "3 Input Processing"
              href: 1-whats-new/v9-whats-new/2022-11-01/3-inputprocessing.qmd
            - text: "7 Mode Choice"
              href: 1-whats-new/v9-whats-new/2022-11-01/7-mc.qmd
        - section: '2022-10-05'
          contents:
            - text: "1 General Parameters - Comparison with v8.3.2"
              href: 1-whats-new/v9-whats-new/2022-10-05/1-genparams.qmd  
            - text: "2 Input Data"
              href: 1-whats-new/v9-whats-new/2022-10-05/2-inputdata.qmd
            - text: "3 Input Processing"
              href: 1-whats-new/v9-whats-new/2022-10-05/3-inputprocessing.qmd
            - text: "4 Household Disaggregation and Auto Ownership"
              href: 1-whats-new/v9-whats-new/2022-10-05/4-hhdisag.qmd
            - text: "7 Mode Choice"
              href: 1-whats-new/v9-whats-new/2022-10-05/7-mc.qmd
            - text: "8 Highway Assignment"
              href: 1-whats-new/v9-whats-new/2022-10-05/8-assign.qmd
            - text: "10 Model Results - Comparison with v8.3.2"
              href: 1-whats-new/v9-whats-new/2022-10-05/10-modelresults.qmd  
    - id: v831-wn-index
      title: "What's New? - Version 8.3.1"
    - id: v831-cv-index
      title: "Calibration/Validation - Version 8.3.1"
    - id: v6-index
      title: "Complete Model Documentation - Version 6"
    - id: v7-index
      title: "Complete Model Documentation - Version 7"
    - id: testing-index
      title: "Testing Environment"
      contents:
        - text: "Jupyter Widgets"
          href: 5-testing/jupyter-widgets.qmd
        - text: "Example OJS"
          href: 5-testing/ojs-test.qmd

format:
  html:
    toc: true
    theme:
      - cerulean
      - custom.css
    code-fold: true
  pdf:
    documentclass: scrreprt




